# Generated by Django 3.2.11 on 2022-01-23 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=30, unique=True)),
                ('screen_name', models.CharField(max_length=30, unique=True)),
                ('login_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('spread_sheet_id', models.CharField(max_length=50)),
                ('CONSUMER_KEY', models.CharField(max_length=100, unique=True)),
                ('CONSUMER_SECRET', models.CharField(max_length=100, unique=True)),
                ('ACCESS_TOKEN', models.CharField(max_length=100, unique=True)),
                ('ACCESS_TOKEN_SECRET', models.CharField(max_length=100, unique=True)),
                ('gcp_api_key', models.CharField(max_length=100)),
                ('bq_project_id', models.CharField(max_length=50)),
                ('bq_dataset_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'twitter_sender',
            },
        ),
    ]
