# Generated by Django 3.2.11 on 2022-01-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_add_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittersender',
            name='GCP_account_key_upload',
            field=models.FileField(default='social-dmer.json', upload_to='GCP_account_keys/'),
        ),
    ]
