# Generated by Django 3.2.11 on 2022-01-31 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_add_GCP_account_key_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twittersender',
            name='login_id',
        ),
    ]
