# Generated by Django 3.2.11 on 2022-01-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_delete_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittersender',
            name='GCP_account_key_upload',
            field=models.FileField(default='GCP_account_keys/social-dmer.json', upload_to='GCP_account_keys/'),
        ),
    ]
