# Generated by Django 3.2.11 on 2022-02-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_edit_GCP_account_key_upload_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittersender',
            name='is_zendesk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twittersender',
            name='zendesk_api_key',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='twittersender',
            name='zendesk_email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='twittersender',
            name='zendesk_subdomain',
            field=models.CharField(default='', max_length=50),
        ),
    ]
