# Generated by Django 3.2.11 on 2022-02-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0005_add_zendesk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittersender',
            name='GCP_account_key_upload',
            field=models.FileField(default='GCP_account_keys/serviceーaccount-key.json', upload_to='GCP_account_keys/'),
        ),
    ]
