# Generated by Django 3.2.11 on 2022-04-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0006_change_GCP_account_key_upload_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittersender',
            name='GCP_account_key_upload',
            field=models.FileField(default='GCP_account_keys/service-account-key.json', upload_to='GCP_account_keys/'),
        ),
    ]
