# Generated by Django 3.2.11 on 2022-06-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0007_change_account_key_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittersender',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
