# Generated by Django 3.2.11 on 2022-04-13 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sender', '0006_change_GCP_account_key_upload_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterReceiveDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_dm_sender_id', models.CharField(max_length=255)),
                ('receive_dm_sender_name', models.CharField(max_length=255)),
                ('msg_text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.twittersender')),
            ],
            options={
                'db_table': 'receive_dm',
            },
        ),
    ]
