# Generated by Django 3.2.11 on 2022-01-23 10:27

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('company', models.CharField(blank=True, max_length=30, verbose_name='company')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('profile', models.CharField(blank=True, max_length=255, verbose_name='profile')),
                ('introduction', models.CharField(blank=True, max_length=255, verbose_name='introduction')),
                ('avatar', models.CharField(blank=True, max_length=255, verbose_name='avatar')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'db_table': 'user',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
    ]
