# Generated by Django 3.2.11 on 2022-02-23 23:48

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_add_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check_list',
            field=models.JSONField(default=user.models.get_check_list_default),
        ),
    ]
