# Generated by Django 3.2.11 on 2022-02-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_add_check_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='slack_id'),
        ),
    ]
