# Generated by Django 3.2.11 on 2022-02-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_add_slack_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='check_list',
        ),
        migrations.AddField(
            model_name='user',
            name='is_account_analyze',
            field=models.BooleanField(default=False),
        ),
    ]
