# Generated by Django 3.2.11 on 2022-04-12 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_change_avatar_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='hobby',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image_1'),
        ),
        migrations.AddField(
            model_name='user',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image_2'),
        ),
        migrations.AddField(
            model_name='user',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image_3'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_liver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
