# Generated by Django 3.2.11 on 2022-04-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_add_liver_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
