# Generated by Django 3.2.11 on 2022-06-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_account_analyze',
        ),
    ]
