# Generated by Django 3.2.11 on 2022-06-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_add_upload_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='livers/', verbose_name='image_1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='livers/', verbose_name='image_2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='livers/', verbose_name='image_3'),
        ),
    ]
