# Generated by Django 3.2.11 on 2022-06-29 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_add_line_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sent_dm_type',
            field=models.CharField(default='', max_length=5, verbose_name='DM手動/自動'),
        ),
        migrations.AddField(
            model_name='user',
            name='live_app',
            field=models.CharField(default='', max_length=30, verbose_name='配信アプリ'),
        ),
        migrations.AddField(
            model_name='user',
            name='liver_id',
            field=models.CharField(default='', max_length=30, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='liver_kinds',
            field=models.CharField(default='', max_length=20, verbose_name='ライバー種別'),
        ),
        migrations.AddField(
            model_name='user',
            name='prefecture',
            field=models.CharField(default='', max_length=5, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(default='', max_length=30, verbose_name='職業'),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='', max_length=30, verbose_name='本名'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral',
            field=models.CharField(default='', max_length=30, verbose_name='経路'),
        ),
        migrations.AddField(
            model_name='user',
            name='responsible_manager',
            field=models.CharField(default='', max_length=50, verbose_name='担当マネ'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='', max_length=5, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='user',
            name='start_live_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start_live_date'),
        ),
    ]
