# Generated by Django 3.2.11 on 2022-07-14 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_add_colomns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_sent_dm_type',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='DM手動/自動'),
        ),
        migrations.AlterField(
            model_name='user',
            name='line_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='live_app',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='配信アプリ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liver_id',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='ライバーID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liver_kinds',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ライバー種別'),
        ),
        migrations.AlterField(
            model_name='user',
            name='prefecture',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='職業'),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='本名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='経路'),
        ),
        migrations.AlterField(
            model_name='user',
            name='responsible_manager',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='担当マネ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_live_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='start_live_date'),
        ),
    ]
