# Generated by Django 3.2.11 on 2022-07-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_add_blank_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobby',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
