# Generated by Django 3.2.11 on 2022-07-14 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_add_blank_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
