# Generated by Django 3.2.11 on 2022-07-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_add_blank_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_liver',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
