# Generated by Django 3.2.11 on 2022-07-19 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_null_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobby',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='livers/', verbose_name='image_1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='livers/', verbose_name='image_2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='livers/', verbose_name='image_3'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_liver',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_sent_dm_type',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='DM手動/自動'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='line_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='live_app',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='配信アプリ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liver_id',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='ライバーID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liver_kinds',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='ライバー種別'),
        ),
        migrations.AlterField(
            model_name='user',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='prefecture',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='職業'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='本名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='経路'),
        ),
        migrations.AlterField(
            model_name='user',
            name='responsible_manager',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='担当マネ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='user',
            name='slack_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='slack_id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_live_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='start_live_date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='username'),
        ),
    ]
