# Generated by Django 3.2.11 on 2022-10-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_add_blank_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_top_liver',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
