# Generated by Django 3.2.11 on 2022-01-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterSendDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_screen_name', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=50)),
                ('target_name', models.CharField(max_length=50)),
                ('target_screen_name', models.CharField(max_length=50)),
                ('target_description', models.TextField()),
                ('target_follow_count', models.IntegerField(default=0)),
                ('target_followers_count', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('send_result', models.CharField(max_length=10)),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'twitter_send_dm',
            },
        ),
    ]
